###########################################################
###########################################################
####                    Mine Quizz                     ####
####                   Configuration                   ####
###########################################################
###########################################################



###########################################################
###########################################################
####                    Mine Quizz                     ####
####                    ScoreBoard                     ####
###########################################################
###########################################################

# Les placeholder pour le scoreboard sont les suivant:
#[playername], [lp_prefix], [lp_sufix], [online_player], [quizz_point], [date_time]
# color : &
#
scoreboard:
  name: "&f&lJeanCraft" # Nom affiché en haut du scoreboard
  line:
    8: "&7[date_time]"
    7: ""
    6: "&fGrade : &r[lp_prefix]"
    5: "&fPseudo : &a[playername]"
    4: "&fPoints : &a[quizz_point]"
    3: "   "
    2: "&fJoueurs : &a[online_player]"
    1: "  "
    0: "&ejeancraft.fr"
